#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jing Haihan
"""Export named abilities through feth-save-editor's catalog command."""
import argparse
import re
from pathlib import Path
from export_names import ROOT, LANGUAGES, catalog, literal

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('editor', type=Path)
editor = parser.parse_args().editor.resolve()
names = [catalog(editor, 'abilities', language) for language in LANGUAGES]
for table in names:
    for key, name in table.items():
        table[key] = re.sub(r'^\[\d+ - ', '', name).removesuffix(']')
ids = [key for key, name in sorted(names[0].items())
       if key < 240 and name not in ('TBD', 'Missing Number', '----', '')]
lines = ['// Generated by scripts/export_abilities.py. Do not edit.',
         '// Game text from feth-save-editor; original data retains its authorship.',
         '#include "feth/core/abilities.hpp"', 'namespace feth::core {', 'namespace {',
         'constexpr AbilityId kIds[] = {' + ', '.join(map(str, ids)) + '};',
         'struct Name { AbilityId id; const char* names[3]; };',
         'constexpr Name kNames[] = {']
for key in ids:
    lines.append('  {' + str(key) + ', {' + ', '.join(literal(table[key]) for table in names) + '}},')
lines += ['};', '} // namespace',
          'std::span<const AbilityId> ability_ids() { return kIds; }',
          'std::string ability_name(AbilityId id, Locale locale) {',
          '  for (const auto& entry : kNames) {',
          '    if (entry.id == id) return entry.names[static_cast<unsigned>(locale)];',
          '  }', '  return "ID " + std::to_string(id);', '}', '} // namespace feth::core', '']
(ROOT / 'source/generated/ability_catalog.cpp').write_text('\n'.join(lines))
