#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jing Haihan
"""Export the save editor's obtainable battalion templates and names."""
import argparse
import json
import re
from pathlib import Path
from export_names import ROOT, LANGUAGES, catalog, literal

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('editor', type=Path)
editor = parser.parse_args().editor.resolve()
templates = [tuple(map(int, entry)) for entry in re.findall(
    r'\((\d+), (\d+), (\d+)\)',
    (editor / 'core/ObtainableBattalions.cs').read_text())]
names = [catalog(editor, 'battalions', language) for language in LANGUAGES]
lines = ['// Generated by scripts/export_battalions.py. Do not edit.',
         '// Templates from jinghaihan/feth-save-editor (MIT); game text retains its authorship.',
         '#include "feth/core/battalions.hpp"', 'namespace feth::core {', 'namespace {',
         'constexpr BattalionTemplate kTemplates[] = {']
for kind, stamina, skill in templates:
    lines.append(f'  {{{kind}, {stamina}, {skill}}},')
lines += ['};', 'struct Name { unsigned id; const char* names[3]; };',
          'constexpr Name kNames[] = {']
for kind in sorted(names[0]):
    labels = [table[kind] for table in names]
    labels = [re.sub(r'^\[?\d+ - ', '', label).rstrip(']') for label in labels]
    lines.append('  {' + str(kind) + ', {' + ', '.join(map(literal, labels)) + '}},')
lines += ['};', '} // namespace',
          'std::span<const BattalionTemplate> battalion_templates() { return kTemplates; }',
          'std::string battalion_name(std::uint8_t type, Locale locale) {',
          '  for (const auto& entry : kNames) {',
          '    if (entry.id == type) return entry.names[static_cast<unsigned>(locale)];',
          '  }', '  return "ID " + std::to_string(type);', '}', '} // namespace feth::core', '']
(ROOT / 'source/generated/battalion_catalog.cpp').write_text('\n'.join(lines))
