#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jing Haihan

"""Export the save editor's v1.2.0 item durability database."""

import argparse
import gzip
import struct
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('editor', type=Path)
args = parser.parse_args()
data = gzip.decompress((args.editor / 'core/Resources/fixed_data.bin.gz').read_bytes())
entries = []
for table, base_id in enumerate((10, 4000, 5000, 6000, 7000, 600, 1000)):
    offset, size = struct.unpack_from('<II', data, 4 + table * 8)
    table_data = data[offset:offset + size]
    count, stride = struct.unpack_from('<II', table_data, 4)
    for index in range(count):
        # ITEM_DATABASE_ENTRY.Durability is byte 0x0B, after the 0x40-byte header.
        durability = table_data[0x40 + index * stride + 0x0B]
        if durability:
            entries.append((base_id + index, durability))

lines = [
    '// Generated by scripts/export_item_data.py. Do not edit.',
    '// Values from feth-save-editor; original game data retains its authorship.',
    '#include "feth/core/items.hpp"',
    '', 'namespace feth::core {', 'namespace {',
    'struct DurabilityEntry { ItemId id; ItemDurability maximum; };',
    'constexpr DurabilityEntry kDurability[] = {',
]
lines.extend(f'  {{{item_id}, {maximum}}},' for item_id, maximum in sorted(entries))
lines.extend([
    '};', '}  // namespace', '',
    'std::optional<ItemDurability> normal_item_durability(ItemId id) {',
    '  for (const auto& entry : kDurability) {',
    '    if (entry.id == id) return entry.maximum;',
    '  }', '  return std::nullopt;', '}', '',
    '}  // namespace feth::core', '',
])
root = Path(__file__).resolve().parents[1]
(root / 'source/generated/item_data.cpp').write_text('\n'.join(lines))
print(f'Exported {len(entries)} item durability values')
