#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jing Haihan

"""Export names through feth-save-editor's existing catalog command."""

import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ('en_u', 'zh_hans', 'jp')


def catalog(editor, kind, language):
    dll = editor / 'cli/bin/Release/net10.0/FethEditor.Cli.dll'
    output = subprocess.check_output([
        'dotnet', str(dll), 'catalog', '--type', kind, '--language', language,
    ], text=True)
    entries = {}
    for entry in json.loads(output):
        if entry['id'] < 0:
            continue
        name = entry['name']
        if kind in ('items', 'characters'):
            name = name.partition(' - ')[2] or name
        entries[entry['id']] = name
    return entries


def literal(value):
    return json.dumps(value, ensure_ascii=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('editor', type=Path, help='feth-save-editor checkout')
    args = parser.parse_args()
    editor = args.editor.resolve()
    subprocess.run(['dotnet', 'build', str(editor / 'cli/Cli.csproj'),
                    '-c', 'Release', '--nologo'], check=True, stdout=subprocess.DEVNULL)
    revision = subprocess.check_output(
        ['git', '-C', str(editor), 'rev-parse', 'HEAD'], text=True).strip()

    tables = {}
    for kind in ('items', 'classes', 'characters'):
        languages = [catalog(editor, kind, language) for language in LANGUAGES]
        tables[kind] = [
            {'id': key, 'names': [language[key] for language in languages]}
            for key in sorted(languages[0])
        ]

    provenance = {'repository': 'https://github.com/jinghaihan/feth-save-editor',
                  'revision': revision, 'languages': LANGUAGES}
    (ROOT / 'assets/localization/names.json').write_text(
        json.dumps({'source': provenance, **tables}, ensure_ascii=False, indent=2) + '\n')
    generate(tables)


def generate(tables):
    lines = [
        '// Generated by scripts/export_names.py. Do not edit.',
        '// Game text from feth-save-editor; original data retains its authorship.',
        '#include "feth/core/names.hpp"',
        '', 'namespace feth::core {', 'namespace {',
        'struct NamedEntry { unsigned id; const char* names[3]; };',
    ]
    for kind in ('items', 'classes', 'characters'):
        if kind == 'characters':
            continue
        lines.append(f'constexpr NamedEntry k{kind.title()}[] = {{')
        for entry in tables[kind]:
            names = ', '.join(literal(name) for name in entry['names'])
            lines.append(f'  {{{entry["id"]}, {{{names}}}}},')
        lines.append('};')

    # Support pairs use upstream English names as stable keys, not translated keys.
    characters = {}
    for entry in tables['characters']:
        names = entry['names']
        characters.setdefault(names[0], names)
        if names[0].endswith(('♂', '♀')):
            characters.setdefault(names[0][:-1], [name.rstrip('♂♀') for name in names])
    lines.extend(['struct CharacterName { const char* names[3]; };',
                  'constexpr CharacterName kCharacters[] = {'])
    for names in sorted(characters.values()):
        lines.append('  {{' + ', '.join(literal(name) for name in names) + '}},')
    lines.extend([
        '};', '',
        'template <std::size_t N>',
        'const char* lookup(const NamedEntry (&entries)[N], unsigned id, Locale locale) {',
        '  for (const auto& entry : entries) {',
        '    if (entry.id == id) return entry.names[static_cast<unsigned>(locale)];',
        '  }', '  return nullptr;', '}', '', '}  // namespace', '',
        'std::string item_name(ItemId id, Locale locale) {',
        '  const auto* name = lookup(kItems, id, locale);',
        '  return name != nullptr ? name : "ID " + std::to_string(id);', '}', '',
        'std::string class_name(ClassId id, Locale locale) {',
        '  const auto* name = lookup(kClasses, id, locale);',
        '  return name != nullptr ? name : "ID " + std::to_string(id);', '}', '',
        'std::string character_name(std::string_view english, Locale locale) {',
        '  for (const auto& entry : kCharacters) {',
        '    if (entry.names[0] == english) return entry.names[static_cast<unsigned>(locale)];',
        '  }', '  return std::string(english);', '}', '',
        '}  // namespace feth::core', '',
    ])
    (ROOT / 'source/generated/names.cpp').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
