# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jing Haihan

name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: make -f Makefile.host test

  overlay:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: make -j2
      - uses: actions/upload-artifact@v7
        with:
          name: feth-overlay
          path: feth-overlay.ovl
          if-no-files-found: error
